kind: Deployment
apiVersion: apps/v1
metadata:
  name: azure-build-agent
  namespace: azure-build
  labels:
    app: azure-build-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-build-agent
  template:
    metadata:
      labels:
        app: azure-build-agent
    spec:
      containers:
        - name: openshift-azure-build-agent
          image: 'quay.io/redhat_na_ssa/openshift-azure-build-agent:latest'
          env:
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_TOKEN
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_URL
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_POOL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: azure-build-sa
      serviceAccount: azure-build-sa
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
